<?php

return [

    'services' => [
        'mobile' => 'Mobile',
        'dth' => 'DTH Recharge',
        'electricity' => 'Electricity',
        'insurance' => 'Insurance',
        'water' => 'Water Bill',
        'broadband' => 'Broadband',
        'cable' => 'Cable',
        'credit_card' => 'Credit Card',
        'municipal_tax' => 'Municipal Taxes',
        'fastage' => 'Fastage Recharge',
        'gas_cylinder' => 'Gas Cylinder',
        'loan_repayment' => 'Loan Repayments',
        'lpg_gas' => 'LPG Gas',
        'landline' => 'Landline',
    ],

    'circles' => [
        1 => 'Andhra Pradesh',
        2 => 'Assam',
        3 => 'Bihar & Jharkhand',
        4 => 'Chennai',
        5 => 'Delhi & NCR',
        6 => 'Gujarat',
        7 => 'Haryana',
        8 => 'Himachal Pradesh',
        9 => 'Jammu & Kashmir',
        10 => 'Karnataka',
        11 => 'Kerala',
        12 => 'Kolkata',
        13 => 'Maharashtra & Goa (except Mumbai)',
        14 => 'MP & Chattisgarh',
        15 => 'Mumbai',
        16 => 'North East',
        17 => 'Orissa',
        18 => 'Punjab',
        19 => 'Rajasthan',
        20 => 'Tamilnadu',
        21 => 'UP(EAST)',
        22 => 'UP(WEST) & Uttarakhand',
        23 => 'West Bengal',
        51 => 'All India (except Delhi/Mumbai)',
        201 => 'Agra',
        202 => 'Ahmedabad',
        203 => 'Bhiwandi',
        204 => 'Surat',
        205 => 'Shilmumbrakalwa',
    ],
];
